services:
    web:
        image: lavoweb/php-5.6
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html
            - ./apache/secbydes.conf:/etc/apache2/sites-available/secbydes.conf
        depends_on:
            - db
        command: >
            bash -lc "
              a2enmod rewrite &&
              a2ensite secbydes.conf &&
              a2dissite 000-default.conf || true &&
              apache2-foreground
            "
    db:
        image: mariadb:10.5
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mysql:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql


    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
        depends_on:
            - db
